version: '3.1'

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ai-playground
      MYSQL_USER: ai-playground
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306